version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  build_and_cache_dependencies:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - node/install-packages:
          pkg-manager: npm
      - save_cache:
          paths:
            - ~/project/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  run_api_tests:
    executor: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Ejecutar Pruebas de la API
          command: npm test
workflows:
  build_test_flow:
    jobs:
      - build_and_cache_dependencies
      - run_api_tests:
          requires:
            - build_and_cache_dependencies
